{{- range $k, $v := .Values.reapers }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ $k }}
  namespace: {{$.Release.Namespace}}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    app: {{ $.Chart.Name }}-{{ $k }}
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}-{{ $k }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}-{{ $k }}
        release: {{ $.Release.Name }}
    spec:
      serviceAccountName: pod-reaper-service-account
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          env:
          {{- range $envkey, $envvalue := $v }}
          {{- if $envvalue }}
            - name: {{ upper $envkey}}
              {{- if eq $envkey "required_keys_values"}}
              value: {{$envvalue | toJson }}
              {{ else }}
              value: "{{$envvalue}}"
              {{- end}}
          {{- end }}
          {{- end }}

---

{{- end -}}
