---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}-service-account
  namespace: {{.Release.Namespace}}
{{ end }}
---
# minimal permissions required for running pod-reaper at cluster level
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ $.Chart.Name }}-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["list", "delete"]
- apiGroups:
  - "apps"
  resources:
    - deployments
    - deployments/scale
    - replicasets
    - replicasets/scale
  verbs:
    - delete
    - get
    - list
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
    - deployments
    - deployments/scale
    - replicasets
    - replicasets/scale
  verbs:
    - delete
    - get
    - list
---
# binding the above cluster role (permissions) to the above service account
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $.Chart.Name }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $.Chart.Name }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "chart.serviceAccountName" . }}-service-account
  namespace: {{.Release.Namespace}}
---
